# Generated by Django 3.2.13 on 2022-06-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyVal',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('val', models.IntegerField(default=0)),
            ],
        ),
    ]
