# Generated by Django 3.2.13 on 2022-06-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_val_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyval',
            name='val',
            field=models.IntegerField(default=0),
        ),
    ]
