# Generated by Django 3.2.13 on 2022-06-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doginfo',
            old_name='url',
            new_name='mod_img',
        ),
        migrations.AddField(
            model_name='doginfo',
            name='org_img',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doginfo',
            name='breed',
            field=models.CharField(max_length=500),
        ),
    ]
