# Generated by Django 3.2.13 on 2022-06-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_api', '0002_auto_20220624_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='doginfo',
            name='test_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
